/**
 *
 * Agora Real Time Engagement
 * Created by Zheng, Ender in 2021-08.
 * Copyright (c) 2021 Agora IO. All rights reserved.
 *
 */
#pragma once

typedef enum rte_ap_server_type_t {
  RTE_AP_SERVER_DEFAULT,
  RTE_AP_SERVER_AUTCRYPTO,
  RTE_AP_SERVER_TCPTLS,
  RTE_AP_SERVER_ALL,
} rte_ap_server_type_t;

typedef enum rte_ap_service_t {
  RTE_AP_SERVICE_VOICE = 1,  // UNILBS-VOICE
  RTE_AP_SERVICE_P2P = 2,  // UNILBS-P2P
  RTE_AP_SERVICE_WEBRTC = 3,  // UNILBS-WEBRTC
  RTE_AP_SERVICE_CDS = 4,  // CDS
  RTE_AP_SERVICE_REPORT = 5,  // UNILBS-REPORT
  RTE_AP_SERVICE_TDS = 6,  // TDS
  RTE_AP_SERVICE_SIG = 7,  // UNILBS-SIG
  RTE_AP_SERVICE_UAPAPPCENTER = 8,  // APPCENTER
  RTE_AP_SERVICE_VOET = 9,  // UNILBS-VOET
  RTE_AP_SERVICE_SUA = 10,  // STRING UID ALLOCATOR
  RTE_AP_SERVICE_WEBRTC2 = 11,  // UNILBS-WEBRTC2
  RTE_AP_SERVICE_IMGPREDICTION = 12,  // UNILBS-IMG-PREDICTION
  RTE_AP_SERVICE_RESTY = 13,  // RESTY2
  RTE_AP_SERVICE_UDPPROXY = 14,  // UNILBS-UDP-PROXY
  RTE_AP_SERVICE_TCPPROXY = 15,  // UNILBS-TCP-PROXY
  RTE_AP_SERVICE_TLSPROXY = 16,  // UNILBS-TLS-PROXY
  RTE_AP_SERVICE_AUTVOICE = 17,  // UNILBS-AUT-VOICE
  RTE_AP_SERVICE_WEBPROXY = 18,  // UNILBS-WEB-PROXY
  RTE_AP_SERVICE_DDD = 19,  // UNILBS-DDD
  RTE_AP_SERVICE_DDDSTAGING = 21,  // UNILBS-DDD-STAGING
  RTE_AP_SERVICE_TLSAUTOFALLBACK = 24,  // AUTO FALLBACK TO TCP TLS CLOUD PROXY
  RTE_AP_SERVICE_UDPAUTOFALLBACK = 25,  // AUTO-FALLBACK-TO-UDP-PROXY
} rte_ap_service_t;